# Generated by Django 3.2.9 on 2022-04-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
